### ISSUE TITLE
Setup errors when there are already scripts in place.

### ISSUE THREAD

**Issue by DamnedScholar** [jonathan-s/django-sockpuppet#7]
* Sockpuppet version: 0.1.0
* Django version: 2.2
* Python version: 3.6
* Operating System: Ubuntu 18

### Description

The setup script throws an error when there's already a `build` or `watch` script in `package.json`, even if the script is the same as the one being added. It seems like a check could be put in place to look for these scripts ahead of time, then not call `add-project-script` if it's unnecessary. This would have the added benefit of allowing the script to output an informative error message if a non-matching script was found.

### What I Did

```
› python manage.py initial_sockpuppet

/usr/local/bin/add-project-script -> /usr/local/lib/node_modules/add-project-script/dist/index.js
/usr/local/lib
└─┬ add-project-script@1.0.2
  ├─┬ chalk@2.4.2
  │ ├─┬ ansi-styles@3.2.1
  │ │ └─┬ color-convert@1.9.3
  │ │   └── color-name@1.1.3
  │ ├── escape-string-regexp@1.0.5
  │ └─┬ supports-color@5.5.0
  │   └── has-flag@3.0.0
  ├── commander@2.20.3
  └─┬ jsonfile@4.0.0
    └── graceful-fs@4.2.4

There was an error!
Script with name 'build' already exists!
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/home/damnedscholar/github/devilbox/data/www/c-street/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/damnedscholar/github/devilbox/data/www/c-street/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/damnedscholar/github/devilbox/data/www/c-street/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/damnedscholar/github/devilbox/data/www/c-street/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/damnedscholar/github/devilbox/data/www/c-street/lib/python3.6/site-packages/sockpuppet/management/commands/initial_sockpuppet.py", line 16, in handle
    subprocess.check_call(build, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'add-project-script -n "build" -v "webpack --mode production"' returned non-zero exit status 1.
```

**Comment by jonathan-s** [comment]
Thanks for reporting this!

**Comment by DamnedScholar** [comment]
The solution works in the case that the script is being run in a repository where it has already been run (and solves the error case I ran into), but it doesn't account for the possibility of being run in a project that already uses NPM to build things. There's rarely going to be a `package.json` in the root of a typical Django project, for sure, but people do all sorts of weird things.
